// For each random line, 'b' is to announce the time before the line. 'a' is to announce the time after the line. 'e' is either way.

export const randomLineTimePosition = {
  1: "a",
  2: "e",
  3: "e",
  4: "e",
  5: "a",
  6: "e",
  7: "a",
  8: "b",
  9: "a",
  10: "b",
  11: "e",
  12: "e",
  13: "e",
  14: "e",
  15: "a",
  16: "e",
  17: "e",
  18: "a",
  19: "a",
  20: "e",
  21: "e",
  22: "e",
  23: "e",
};
